using KeyboardSound.Core.SoundPacks;

namespace KeyboardSound.Tests;

public class SoundPackManagerTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), $"ks-packs-{Guid.NewGuid():N}");

    public SoundPackManagerTests()
    {
        Directory.CreateDirectory(_root);
    }

    [Fact]
    public void Discover_FindsValidPack_WithMetadataAndSamples()
    {
        var packDir = CreatePack("creamy", writeMetadata: true);
        WriteSample(packDir, "normal", "click1.wav");
        WriteSample(packDir, "normal", "click2.wav");
        WriteSample(packDir, "space", "thock.wav");

        var packs = new SoundPackManager().Discover(_root);

        var pack = Assert.Single(packs);
        Assert.Equal("creamy", pack.Id);
        Assert.Equal("Creamy", pack.Metadata.Name);
        Assert.Equal(2, pack.SoundsByCategory[SoundCategory.Normal].Count);
        Assert.Single(pack.SoundsByCategory[SoundCategory.Space]);
    }

    [Fact]
    public void Discover_PackWithoutMetadata_FallsBackToFolderName()
    {
        var packDir = CreatePack("nometa", writeMetadata: false);
        WriteSample(packDir, "normal", "a.wav");

        var packs = new SoundPackManager().Discover(_root);

        var pack = Assert.Single(packs);
        Assert.Equal("nometa", pack.Id);
        Assert.Equal("nometa", pack.Metadata.Name);
    }

    [Fact]
    public void Discover_PackWithCorruptMetadata_StillLoadsSamples()
    {
        var packDir = CreatePack("broken", writeMetadata: false);
        File.WriteAllText(Path.Combine(packDir, "pack.json"), "{ not json ]]");
        WriteSample(packDir, "normal", "a.wav");

        var packs = new SoundPackManager().Discover(_root);

        var pack = Assert.Single(packs);
        Assert.Equal("broken", pack.Id);
    }

    [Fact]
    public void Discover_PackWithNoSamples_IsSkipped()
    {
        CreatePack("empty", writeMetadata: true);

        var packs = new SoundPackManager().Discover(_root);

        Assert.Empty(packs);
    }

    [Fact]
    public void Discover_UnknownCategoryFolder_IsIgnored()
    {
        var packDir = CreatePack("pack", writeMetadata: true);
        WriteSample(packDir, "normal", "a.wav");
        WriteSample(packDir, "notarealcategory", "b.wav");

        var packs = new SoundPackManager().Discover(_root);

        var pack = Assert.Single(packs);
        Assert.Single(pack.SoundsByCategory); // only "normal" recognized
    }

    [Fact]
    public void Discover_NonexistentRoot_ReturnsEmptyWithoutThrowing()
    {
        var packs = new SoundPackManager().Discover(Path.Combine(_root, "does-not-exist"));

        Assert.Empty(packs);
    }

    [Fact]
    public void Discover_WithoutCuratedMetadata_AutoGeneratesStableId()
    {
        var packDir = CreatePack("mypack", writeMetadata: true);
        WriteSample(packDir, "normal", "click_one.wav");

        var pack = Assert.Single(new SoundPackManager().Discover(_root));
        var sound = Assert.Single(pack.Sounds);

        Assert.Equal("mypack_normal_click_one", sound.Id);
        Assert.Equal("Click One", sound.DisplayName);
        Assert.Equal(SoundCategory.Normal, sound.Category);
    }

    [Fact]
    public void Discover_AutoGeneratedId_IsStableAcrossRediscovery()
    {
        var packDir = CreatePack("mypack", writeMetadata: true);
        WriteSample(packDir, "normal", "click_one.wav");
        WriteSample(packDir, "normal", "click_two.wav");

        var manager = new SoundPackManager();
        var firstId = manager.Discover(_root).Single().Sounds.First(s => s.FilePath.EndsWith("click_one.wav")).Id;

        // Adding a new sound and re-discovering must not change the existing sound's id.
        WriteSample(packDir, "normal", "click_three.wav");
        var secondId = manager.Discover(_root).Single().Sounds.First(s => s.FilePath.EndsWith("click_one.wav")).Id;

        Assert.Equal(firstId, secondId);
    }

    [Fact]
    public void Discover_WithCuratedSoundMetadata_UsesCuratedIdAndName()
    {
        var packDir = CreatePack("curated", writeMetadata: false);
        WriteSample(packDir, "normal", "raw-file-name.wav");
        File.WriteAllText(Path.Combine(packDir, "pack.json"), """
            {
              "id": "curated",
              "name": "Curated",
              "sounds": [
                { "id": "stable_id_01", "displayName": "Ultra Creamy", "category": "Normal", "file": "normal/raw-file-name.wav" }
              ]
            }
            """);

        var pack = Assert.Single(new SoundPackManager().Discover(_root));
        var sound = Assert.Single(pack.Sounds);

        Assert.Equal("stable_id_01", sound.Id);
        Assert.Equal("Ultra Creamy", sound.DisplayName);
    }

    [Fact]
    public void Discover_CuratedMetadataReferencingMissingFile_IsIgnoredWithoutThrowing()
    {
        var packDir = CreatePack("curated", writeMetadata: false);
        WriteSample(packDir, "normal", "a.wav");
        File.WriteAllText(Path.Combine(packDir, "pack.json"), """
            {
              "id": "curated",
              "name": "Curated",
              "sounds": [
                { "id": "ghost_01", "displayName": "Ghost", "category": "Normal", "file": "normal/does-not-exist.wav" }
              ]
            }
            """);

        var pack = Assert.Single(new SoundPackManager().Discover(_root));

        // The real file is still discovered (auto id); the dangling curated entry produces
        // no phantom sound and does not crash discovery.
        var sound = Assert.Single(pack.Sounds);
        Assert.NotEqual("ghost_01", sound.Id);
    }

    private string CreatePack(string id, bool writeMetadata)
    {
        var dir = Path.Combine(_root, id);
        Directory.CreateDirectory(dir);
        if (writeMetadata)
        {
            var name = char.ToUpperInvariant(id[0]) + id[1..];
            File.WriteAllText(Path.Combine(dir, "pack.json"),
                $"{{ \"id\": \"{id}\", \"name\": \"{name}\", \"author\": \"Test\", \"version\": \"1.0.0\" }}");
        }
        return dir;
    }

    private static void WriteSample(string packDir, string category, string fileName)
    {
        var categoryDir = Path.Combine(packDir, category);
        Directory.CreateDirectory(categoryDir);
        // Content doesn't matter for discovery — only decoded when a pack is activated.
        File.WriteAllBytes(Path.Combine(categoryDir, fileName), new byte[] { 0x00 });
    }

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, recursive: true);
    }
}
